# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/
require 'open-uri'

app_version "1.2.0"

# modify the following parameter for different purpose
skip_app_version_update true
skip_screenshots true
skip_binary_upload false
skip_metadata true
overwrite_screenshots false
phased_release true

# change the path to the fold in your system
metadata_path "fastlane/metadata"
screenshots_path "fastlane/screenshots"