# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test on iphone 8 plus and iPad Air"
  lane :tests do
    run_tests(devices: ["iPhone 8 Plus", "iPad Pro (12.9-inch) (3rd generation)"])
    end

    lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

  lane :release do
  build_app(scheme: "TianganDizhi",
            include_bitcode: true)
	end
end
