# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :mac do
  desc "Push metadata to the Mac App Store"
  lane :metadata do
    deliver(
      app_identifier: "com.uriphium.TianganDizhi",
      platform: "osx",
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      metadata_path: "fastlane/metadata"
    )
  end

  desc "Push a new release build to the Mac App Store"
  lane :release do
    build_app(
      scheme: "TianganDizhi",
      destination: "generic/platform=macOS",
      export_method: "app-store"
    )
    deliver(
      app_identifier: "com.uriphium.TianganDizhi",
      platform: "osx",
      skip_metadata: false,
      skip_screenshots: true,
      metadata_path: "fastlane/metadata"
    )
  end
end

platform :ios do
  desc "Test on iphone 8 plus and iPad Air"
  lane :tests do
    run_tests(scheme: "TianganDizhi", devices: ["iPhone 8 Plus", "iPad Pro (12.9-inch) (3rd generation)"])
    end

    lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end

  desc "Push metadata only to the iOS App Store"
  lane :metadata do
    deliver(
      skip_binary_upload: true,
      skip_screenshots: true,
      skip_app_version_update: true,
      metadata_path: "fastlane/metadata"
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do
  build_app(scheme: "TianganDizhi",
            include_bitcode: true)
    upload_to_app_store
  end

end
